sass/dart-sass

CHANGELOG.md, lib/src/environment.dart, pubspec.yaml
=> Fix a bug where names were broken through imports.

lib/src/ast/selector/list.dart
If a child selector list contained one complex selector with & and one
without, the latter's parent wouldn't be added automatically.
Closes #28
=> Fix parent selector resolution.

lib/src/functions.dart
=> Properly declare arguments for opacify et al.

lib/src/ast/sass/expression/binary_operation.dart, lib/src/parse/stylesheet.dart, lib/src/value.dart, lib/src/visitor/perform.dart
See sass/sass-spec#968
Closes #31
=> Support the Microsoft-style = operator.

CHANGELOG.md, lib/src/ast/sass/expression/string.dart, lib/src/parse/parser.dart, lib/src/parse/selector.dart, lib/src/parse/stylesheet.dart
=> Add support for Unicode ranges.

lib/src/extend/functions.dart
=> Fix an extend bug with combinators.

lib/src/parse/stylesheet.dart, lib/src/visitor/serialize.dart
=> Fix bracketed-list parsing.

lib/src/visitor/perform.dart
=> Fix @debug output.

CHANGELOG.md, lib/src/extend/functions.dart
=> Fix some extend bugs.

README.md
=> Update Pub package version in README

CHANGELOG.md, lib/src/functions.dart
=> Allow saturate($number).

CHANGELOG.md, lib/src/visitor/perform.dart
=> Set mixin/function arguments locally.

CHANGELOG.md, lib/src/parse/stylesheet.dart
=> Allow #{...}--1.

lib/src/extend/extender.dart
=> Improve the error message for a failed @extend.

CHANGELOG.md, lib/src/ast/css/node.dart, lib/src/visitor/perform.dart
=> Support CSS import reordering.

lib/src/value/number.dart
See sass/sass-spec#999
See sass/sass#2143
=> Fix dp unit conversions.

CHANGELOG.md, lib/src/functions.dart, lib/src/value.dart, lib/src/value/string.dart, pubspec.yaml
See sass/sass-spec#1002
See sass/sass#2175
=> Support var() in plain CSS color functions.

CHANGELOG.md, lib/src/functions.dart, lib/src/value/string.dart
See sass/sass#2211
See sass/sass-spec#1010
=> Fix str-slice().

CHANGELOG.md, lib/src/functions.dart
=> Don't crash in *-color().

CHANGELOG.md, lib/src/visitor/perform.dart
=> Fix newlines in interpolation.

CHANGELOG.md, lib/src/extend/extender.dart
=> Fix a few extend issues.

CHANGELOG.md, lib/src/extend/extender.dart, pubspec.yaml
=> Fix more extend bugs.

CHANGELOG.md, lib/src/functions.dart
=> Fix str-insert() with negative indices.

lib/src/parse/sass.dart
=> Fix some indented syntax bugs.

CHANGELOG.md, lib/sass.dart, lib/src/ast/sass/expression/string.dart, lib/src/executable.dart, lib/src/extend/functions.dart, lib/src/interpolation_buffer.dart, lib/src/io/interface.dart, lib/src/io/node.dart, lib/src/io/vm.dart, lib/src/parse/stylesheet.dart, lib/src/utils.dart, lib/src/value/number.dart, lib/src/visitor/perform.dart
=> Fix a bunch of failing specs.

.travis.yml, tool/grind.dart
=> Fix analysis errors in tool/grind.dart.

CHANGELOG.md, lib/src/parse/at_root_query.dart, lib/src/parse/parser.dart, lib/src/parse/stylesheet.dart, lib/src/visitor/perform.dart, pubspec.yaml
=> More bug fixes.

CHANGELOG.md, README.md, lib/src/ast/css/media_query.dart, lib/src/extend/extender.dart, lib/src/extend/state.dart, lib/src/visitor/perform.dart
=> Forbid extending across media queries.

package/chocolatey/[Content_Types].xml, package/chocolatey/chocolateyInstall.ps1, package/chocolatey/chocolateyUninstall.ps1, package/chocolatey/rels.xml, package/chocolatey/sass.bat, pubspec.yaml, tool/grind.dart
=> Add support for building a Chocolatey package.

lib/src/ast/selector/id.dart, lib/src/extend/functions.dart
=> Fix ID equality.

CHANGELOG.md, lib/src/ast/selector/list.dart, lib/src/functions.dart, lib/src/parse/selector.dart, lib/src/parse/stylesheet.dart, lib/src/visitor/perform.dart
=> Bug fixes.

CHANGELOG.md, README.md, lib/src/ast/css/style_rule.dart, lib/src/ast/selector.dart, lib/src/ast/selector/complex.dart, lib/src/ast/selector/compound.dart, lib/src/ast/selector/list.dart, lib/src/ast/selector/placeholder.dart, lib/src/ast/selector/pseudo.dart, lib/src/functions.dart, lib/src/parse/stylesheet.dart, lib/src/util/character.dart, lib/src/value/color.dart, lib/src/value/number.dart, lib/src/value/string.dart, lib/src/visitor/perform.dart, lib/src/visitor/serialize.dart
=> Fix more bugs.

CHANGELOG.md, lib/src/extend/functions.dart, pubspec.yaml
=> Update namespace extend per sass/sass#2229.

CHANGELOG.md, lib/src/value/number.dart, lib/src/visitor/perform.dart, pubspec.yaml
=> More sass-spec fixes.

CHANGELOG.md, README.md, lib/src/extend/functions.dart
=> Sass spec fixes.

CHANGELOG.md, lib/src/parse/stylesheet.dart
=> Fix @supports (not ...).

CHANGELOG.md, lib/src/ast/sass/expression/string.dart, lib/src/parse/parser.dart, lib/src/parse/stylesheet.dart
=> Fix a number of small bugs.

CHANGELOG.md, lib/src/extend/extender.dart, lib/src/extend/functions.dart, lib/src/parse/selector.dart
See sass/sass#2266
See sass/sass-spec#1150
=> Support ::slotted().

CHANGELOG.md, lib/src/visitor/serialize.dart
Closes #1782
See sass/sass-spec#1153
=> Emit transparent colors in rgba format

CHANGELOG.md, lib/sass.dart, lib/src/node.dart, lib/src/node/render_error.dart, lib/src/node/render_options.dart, lib/src/render.dart, test/node_api_test.dart
Also add renderString to the Dart API.
Partially addresses #7
=> Add support for the data option to the JS API

lib/src/node.dart, lib/src/node/render_options.dart, lib/src/render.dart, test/node_api_test.dart
=> Support indentedSyntax in the JS API

CHANGELOG.md, lib/src/node.dart, lib/src/node/render_options.dart, lib/src/render.dart, lib/src/visitor/perform.dart, test/hybrid.dart, test/node_api_test.dart
=> Support includePaths in the JS API

lib/sass.dart, lib/src/compile.dart, lib/src/node.dart, lib/src/node/render_result.dart, lib/src/visitor/evaluate.dart, test/node_api_test.dart
=> Fully support the return value for the Node render() functions

CHANGELOG.md, lib/src/exception.dart, lib/src/executable.dart, lib/src/node.dart, lib/src/node/render_error.dart, lib/src/utils.dart, lib/src/visitor/evaluate.dart, test/cli_shared.dart, test/node_api_test.dart
=> Fully support the error value for the Node render() functions

CHANGELOG.md, lib/src/executable.dart, lib/src/io/interface.dart, lib/src/io/node.dart, test/cli_shared.dart
=> Produce better messages for non-Sass errors

CHANGELOG.md, lib/src/parse/stylesheet.dart
See sass/sass-spec#1166
Closes #170
=> Properly parse numbers with exponents

CHANGELOG.md, lib/src/ast/css/declaration.dart, lib/src/visitor/serialize.dart, pubspec.yaml
Closes #176
See sass/sass-spec#1169
=> Don't crash on a fully-interpolated CSS variable name

pubspec.yaml, tool/grind.dart
Made possible by daftspaniel/Chocolatey-Packages#10
=> Support dev SDKs on Chocolatey

CHANGELOG.md, lib/src/extend/extender.dart, pubspec.yaml
Closes #191
See sass/sass-spec#1187
=> Fix a crash when extending :not(...) into :not(:not(...))

lib/src/environment.dart, lib/src/functions.dart, lib/src/visitor/evaluate.dart
This will make it easier to have separate synchronous and asynchronous
Environment classes.
=> Define core functions declaratively

lib/src/environment.dart, lib/src/visitor/evaluate.dart, pubspec.yaml, test/synchronize_test.dart, tool/grind.dart, tool/synchronize.dart
=> Compile asynchronous code to synchronous

CHANGELOG.md, lib/src/parse/parser.dart, lib/src/parse/sass.dart, lib/src/parse/stylesheet.dart
=> Support unquoted imports in the indented syntax

CHANGELOG.md, lib/src/util/number.dart, pubspec.yaml
See sass/sass#2409
See sass/sass-spec#1191
=> Fix round() for negative numbers

CHANGELOG.md, lib/src/parse/stylesheet.dart, pubspec.yaml
See sass/sass#2429
See sass/sass-spec#1192
=> Emit a warning for &&

CHANGELOG.md, lib/src/functions.dart, lib/src/value.dart, lib/src/value/string.dart
See sass/sass#2440
See sass/sass-spec#1194
=> Allow var() in place of multiple arguments to color functions

lib/src/visitor/serialize.dart
This improves formatting and fixes a case where it crashed on trailing
whitespace.
See sass/sass-spec#1203
=> Clean up _writeWithIndent()

CHANGELOG.md, lib/src/value/number.dart
=> Fix some unit math issues

tool/app-snapshot-input.scss, tool/grind.dart
Might as well give some subset of our users a speed-up while we wait
for dart-lang/sdk#28617.
=> Generate app snapshots for the current OS

README.md, tool/grind.dart
Technically Homebrew support was added by sass/homebrew-sass@83b7db9, but this makes it official by documenting it and adding a semi-automated update process.
Closes #97 
Closes #104
=> Add Homebrew support

CHANGELOG.md, lib/src/interpolation_buffer.dart, lib/src/parse/parser.dart, lib/src/parse/sass.dart, lib/src/util/character.dart, pubspec.yaml
=> Fix loud comment parsing in the indented syntax

CHANGELOG.md, lib/src/parse/sass.dart
Closes #87
See sass/sass-spec#1216
=> Properly handle hard tabs in the indented syntax

AUTHORS, CHANGELOG.md, lib/src/importer/utils.dart, pubspec.yaml
Ref to: https://github.com/sass/sass/pull/2456
I've not done Dart before so any help will be accepted.
See sass/sass-spec#1206
=> Implement Index and a default file if directory given in import

CHANGELOG.md, lib/src/executable.dart, test/cli_shared.dart
=> Add support for the --load-path flag

CHANGELOG.md, lib/src/executable.dart, test/cli_shared.dart
=> Add an --indented flag

CHANGELOG.md, lib/src/value/number.dart
Closes #254
See sass/sass-spec#1229
=> Allow mod 0

CHANGELOG.md, lib/src/ast/css/media_query.dart, lib/src/parse/media_query.dart
Closes #244
See sass/sass-spec#1230
=> Fix media query merging

CHANGELOG.md, lib/src/parse/parser.dart, lib/src/parse/stylesheet.dart, pubspec.yaml
See https://github.com/sass/sass-spec/pull/1236
=> Allow "!" in custom property values

CHANGELOG.md, lib/src/executable.dart, lib/src/io/interface.dart, lib/src/io/node.dart, lib/src/io/vm.dart, pubspec.yaml, test/cli_shared.dart
=> Add support for "sass input.scss output.css"

CHANGELOG.md, lib/src/executable.dart, lib/src/io/interface.dart, lib/src/io/node.dart, lib/src/io/vm.dart, pubspec.yaml, test/cli_shared.dart
=> Create a directory for CSS output if necessary

CHANGELOG.md, lib/src/parse/stylesheet.dart
Closes #290
See sass/sass-spec#1247
=> Properly parse #{$var} -#{$var}

CHANGELOG.md, lib/src/parse/selector.dart, lib/src/visitor/async_evaluate.dart, lib/src/visitor/evaluate.dart, pubspec.yaml
Closes #286
See https://github.com/sass/sass-spec/pull/1248
=> Improve the error message for extending compound selectors.

CHANGELOG.md, lib/sass.dart, lib/src/compile.dart, lib/src/parse/stylesheet.dart, lib/src/util/no_source_map_buffer.dart, lib/src/util/source_map_buffer.dart, lib/src/utils.dart, lib/src/visitor/serialize.dart, pubspec.yaml, test/source_map_test.dart
=> Add a Dart API for source map generation

CHANGELOG.md, README.md, lib/sass.dart, lib/src/ast/css/node.dart, lib/src/compile.dart, lib/src/node.dart, lib/src/node/render_options.dart, lib/src/node/render_result.dart, lib/src/node/utils.dart, lib/src/util/no_source_map_buffer.dart, lib/src/util/source_map_buffer.dart, lib/src/visitor/evaluate.dart, lib/src/visitor/serialize.dart, package.json, test/node_api/source_map_test.dart, tool/synchronize.dart
=> Add a JavaScript API for source map generation

CHANGELOG.md, lib/src/node.dart, test/node_api/importer_test.dart, test/node_api/utils.dart, test/node_api_test.dart
=> Fix a relative import bug in the JS API

lib/src/executable.dart, lib/src/executable_options.dart, lib/src/node.dart, pubspec.yaml, test/cli_shared.dart, test/node_api/source_map_test.dart, test/utils.dart
=> Add CLI source map support

lib/src/ast/css/declaration.dart, lib/src/async_environment.dart, lib/src/compile.dart, lib/src/environment.dart, lib/src/visitor/async_evaluate.dart, lib/src/visitor/evaluate.dart, lib/src/visitor/serialize.dart, test/source_map_test.dart
Closes #2
See https://github.com/sass/sass-spec/pull/1250
=> Track variable declarations for source maps

CHANGELOG.md, lib/src/importer/node/implementation.dart, pubspec.yaml, test/node_api_test.dart
=> Fix relative imports through relative load paths in the Node API

CHANGELOG.md, lib/src/parse/parser.dart, lib/src/parse/scss.dart, pubspec.yaml
Closes #316
See sass/sass-spec#1252
=> Add support for @elseif

CHANGELOG.md, lib/src/executable.dart, lib/src/executable_options.dart, lib/src/io/node.dart, pubspec.yaml, test/cli_shared.dart
=> Support input:output syntax for compiling multiple files at once

lib/src/importer/async.dart
Fixes https://github.com/sass/dart-sass/issues/321.
=> Add details to documentation for implementing an importer

CHANGELOG.md, lib/src/importer/async.dart, lib/src/importer/utils.dart, pubspec.yaml
Closes #335
See sass/sass-spec#1255
=> Error out on ambiguous imports

CHANGELOG.md, lib/src/executable/options.dart, lib/src/logger.dart, pubspec.yaml, test/cli/shared.dart, test/cli/shared/colon_args.dart
=> Don't consider drive separators to be path-separating colons

CHANGELOG.md, lib/src/parse/parser.dart, lib/src/parse/selector.dart, lib/src/parse/stylesheet.dart, lib/src/visitor/async_evaluate.dart, lib/src/visitor/evaluate.dart, pubspec.yaml
=> Forbid empty custom properties

CHANGELOG.md, lib/src/parse/parser.dart, pubspec.yaml
=> Produce better errors when expected tokens are missing

CHANGELOG.md, lib/src/async_import_cache.dart, lib/src/executable.dart, lib/src/executable/compile_stylesheet.dart, lib/src/executable/options.dart, lib/src/executable/watch.dart, lib/src/import_cache.dart, lib/src/io/interface.dart, lib/src/io/node.dart, lib/src/io/vm.dart, lib/src/node/chokidar.dart, lib/src/stylesheet_graph.dart, lib/src/util/multi_dir_watcher.dart, lib/src/util/path.dart, lib/src/util/path_map.dart, package.json, package/package.json, pubspec.yaml, test/cli/dart/watch_test.dart, test/cli/node/watch_test.dart, test/cli/shared/repl.dart, test/cli/shared/watch.dart
=> Add a --watch command

lib/src/executable/watch.dart, lib/src/io/node.dart
This doesn't flake as often on Dart as it does on Node, but it does
flake.
=> Debounce watch events on all platforms

tool/travis/deploy/npm.sh, tool/travis/deploy/pub.sh
Also add messages to make it clear which script is running in which
Travis task.
=> Fix deploy scripts

.travis.yml, tool/grind.dart, tool/grind/bazel.dart, tool/grind/homebrew.dart, tool/grind/utils.dart
Closes bazelbuild/rules_sass#28
=> Deploy to Bazel on release

CHANGELOG.md, lib/src/executable/compile_stylesheet.dart, test/cli/shared/source_maps.dart
=> Ensure that source map comment URLs are relative to the CSS file

CHANGELOG.md, lib/src/async_import_cache.dart, lib/src/import_cache.dart, lib/src/stylesheet_graph.dart, pubspec.yaml, test/cli/shared.dart, test/synchronize_test.dart
=> Fix a bug where we were setting the base URL of stylesheets wrong

.travis.yml, appveyor.yml
Rolling forward is blocked on dart-lang/sdk#33574.
=> Pin Dart to 2.0.0-dev.63

.travis.yml, CHANGELOG.md, pubspec.yaml
This version was set separately than the version we test against, for
some reason.
Closes #380
=> Pin the version of Dart that gets published

CHANGELOG.md, lib/src/parse/parser.dart, lib/src/parse/stylesheet.dart, pubspec.yaml
Partially addresses #378
Closes #372
See sass/sass-spec#1266
=> Fix @-moz-document parsing and add deprecation warnings

CHANGELOG.md, lib/src/executable/options.dart, lib/src/executable/watch.dart, lib/src/io/interface.dart, lib/src/io/node.dart, lib/src/io/vm.dart, lib/src/node/chokidar.dart, lib/src/util/multi_dir_watcher.dart, pubspec.yaml, test/cli/shared/watch.dart
=> Add a --poll option

CHANGELOG.md, lib/src/executable.dart, lib/src/executable/options.dart, lib/src/executable/watch.dart, lib/src/io/node.dart, pubspec.yaml, test/cli/shared/colon_args.dart, test/cli/shared/watch.dart
=> Add a --stop-on-error flag

CHANGELOG.md, lib/src/node/value/color.dart, pubspec.yaml, test/node_api/value/color_test.dart
=> Support Node Sass's sass.types.Color(argb) constructor

tool/grind/bazel.dart
=> Run Yarn after updating the Bazel rule's package.json

CHANGELOG.md, lib/src/io/node.dart, pubspec.yaml
=> Fix --watch option with node on Mac OS

README.md
=> Add an explicit compatibility policy

CHANGELOG.md, lib/src/ast/css/media_query.dart, lib/src/visitor/async_evaluate.dart, lib/src/visitor/evaluate.dart, pubspec.yaml
See sass/sass#1831
See sass/sass-spec#1267
=> Preserve nested media queries when they can't be merged

README.md
=> Remove --devel as it's no longer --devel

CHANGELOG.md, lib/src/node.dart, lib/src/node/render_options.dart, lib/src/node/render_result.dart, pubspec.yaml, test/node_api/utils.dart, test/node_api_test.dart
=> Don't crash when passing includePaths with importer

CHANGELOG.md, lib/src/parse/stylesheet.dart, pubspec.yaml
See sass/sass#1864
See sass/sass-spec#1271
=> Add support for range-form media queries

CHANGELOG.md, lib/src/parse/parser.dart, lib/src/parse/stylesheet.dart
Closes #425
See sass/sass#1542
See sass/sass-spec#1272
=> Normalize escapes in identifiers

CHANGELOG.md, lib/src/parse/stylesheet.dart
See sass/sass#2378
Closes #426
See sass/sass-spec#1274
=> Add support for plain CSS min() and max()

CHANGELOG.md, package/chocolatey/sass.bat, pubspec.yaml
I missed this in c462b82.
Closes #433
=> Pass --no-preview-dart-2 to the Chocolatey script

CHANGELOG.md, lib/src/executable/watch.dart, lib/src/stylesheet_graph.dart, test/cli/shared/watch.dart
=> Don't hang after a syntax error in --watch

CHANGELOG.md, lib/sass.dart, lib/src/ast/sass/statement/stylesheet.dart, lib/src/ast/selector/list.dart, lib/src/async_import_cache.dart, lib/src/compile.dart, lib/src/executable/compile_stylesheet.dart, lib/src/import_cache.dart, lib/src/importer/filesystem.dart, lib/src/importer/result.dart, lib/src/importer/utils.dart, lib/src/node.dart, lib/src/parse/css.dart, lib/src/parse/scss.dart, lib/src/parse/selector.dart, lib/src/parse/stylesheet.dart, lib/src/syntax.dart, lib/src/visitor/async_evaluate.dart, lib/src/visitor/evaluate.dart, pubspec.yaml, test/node_api/importer_test.dart
Closes #424
See https://github.com/sass/sass-spec/pull/1277
=> Add support for plain CSS imports

lib/src/async_environment.dart, lib/src/environment.dart, lib/src/visitor/async_evaluate.dart, lib/src/visitor/evaluate.dart
Closes #443
See sass/sass-spec#1278
=> Use the proper scope for nested imports

CHANGELOG.md, lib/src/visitor/async_evaluate.dart, lib/src/visitor/evaluate.dart, pubspec.yaml
Closes #453
See sass/sass-spec#1279
=> Fix a crash with nested media rules

CHANGELOG.md, lib/src/visitor/async_evaluate.dart, lib/src/visitor/evaluate.dart, pubspec.yaml
Closes #452 
See sass/sass-spec#1280
=> Add support for extending selector lists

CHANGELOG.md, lib/src/parse/css.dart, pubspec.yaml
=> Add support for the single-equals operator in plain CSS

CHANGELOG.md, lib/src/parse/stylesheet.dart, pubspec.yaml
Closes #466
See https://github.com/sass/sass-spec/pull/1283
=> Support browser hacks in plain CSS mode

CHANGELOG.md, lib/src/executable/compile_stylesheet.dart, pubspec.yaml, test/cli/shared/source_maps.dart
=> Fix embedding source maps with non-ASCII characters

CHANGELOG.md, lib/src/parse/stylesheet.dart, pubspec.yaml
Closes #371
See sass/sass-spec#1284
=> Enable full alpha hex support

CHANGELOG.md, lib/src/parse/stylesheet.dart, pubspec.yaml
=> Fix a parsing bug involving nested content blocks

CHANGELOG.md, lib/src/ast/selector/pseudo.dart, lib/src/visitor/serialize.dart, pubspec.yaml
Closes #484
See sass/sass-spec#1289
=> Treat :before et al a pseudo-elements

pubspec.yaml
=> Remove the unused convert dependency

CHANGELOG.md, lib/src/ast/css/at_rule.dart, lib/src/ast/sass/at_root_query.dart, lib/src/ast/sass/expression/parenthesized.dart, lib/src/ast/sass/statement/at_rule.dart, lib/src/parse/css.dart, lib/src/parse/stylesheet.dart, lib/src/visitor/async_evaluate.dart, lib/src/visitor/evaluate.dart, lib/src/visitor/serialize.dart, pubspec.yaml
Closes #496
See sass/sass-spec#1298
=> Add support for interpolation in at-rule names

CHANGELOG.md, lib/src/ast/sass.dart, lib/src/ast/sass/argument_declaration.dart, lib/src/ast/sass/argument_invocation.dart, lib/src/ast/sass/statement/callable_declaration.dart, lib/src/ast/sass/statement/content_block.dart, lib/src/ast/sass/statement/content_rule.dart, lib/src/ast/sass/statement/include_rule.dart, lib/src/ast/sass/statement/mixin_rule.dart, lib/src/async_environment.dart, lib/src/environment.dart, lib/src/parse/stylesheet.dart, lib/src/visitor/async_evaluate.dart, lib/src/visitor/evaluate.dart, lib/src/visitor/interface/statement.dart, lib/src/visitor/recursive_statement.dart
Closes #498
See sass/sass-spec#1299
=> Add support for passing arguments to @content blocks

CHANGELOG.md, lib/src/utils.dart, lib/src/visitor/async_evaluate.dart, lib/src/visitor/evaluate.dart, lib/src/visitor/serialize.dart
Related to sass/ruby-sass#96
See sass/sass-spec#1302
=> Don't trim escaped whitespace

CHANGELOG.md, lib/src/functions.dart, lib/src/utils.dart, lib/src/value/number.dart, lib/src/visitor/async_evaluate.dart, lib/src/visitor/evaluate.dart, lib/src/visitor/serialize.dart, pubspec.yaml
Closes #497
See sass/sass-spec#1303
=> Add support for CSS Color Level 4 rgb() and hsl() syntax

CHANGELOG.md, lib/src/node/value/string.dart, pubspec.yaml, test/node_api/value/string_test.dart
=> Make types.String.prototype.setValue() de-quote a string

CHANGELOG.md, lib/src/ast/css/media_query.dart, lib/src/utils.dart, pubspec.yaml
Closes #537
See sass/sass-spec#1325
=> Properly merge "all and" media queries

.travis.yml, lib/src/importer/node/implementation.dart, pubspec.yaml, tool/grind/npm.dart
=> Compile to JS with -O4

CHANGELOG.md, lib/src/visitor/serialize.dart, test/compressed_test.dart
See https://github.com/sass/sass/issues/649#issuecomment-447033060
=> Don't omit units in numbers in compressed mode

CHANGELOG.md, lib/src/parse/parser.dart
Closes #552
See https://github.com/sass/sass-spec/pull/1332
=> Emit tab characters as \9

CHANGELOG.md, lib/src/value/string.dart, pubspec.yaml
See sass/sass#2584
See https://github.com/sass/sass-spec/pull/1333
=> Add support for new special number strings

CHANGELOG.md, lib/src/parse/parser.dart, pubspec.yaml
See https://github.com/sass/sass-spec/pull/1336
=> Fix a check for adjusting parse errors

CHANGELOG.md, lib/src/executable.dart, lib/src/executable/options.dart, pubspec.yaml, test/cli/shared/colon_args.dart
=> Allow individual directories to be passed on the command-line

CHANGELOG.md, lib/src/parse/stylesheet.dart, pubspec.yaml
Closes #584
See https://github.com/sass/sass-spec/pull/1338
=> Produce a better error for invalid function contents

lib/src/ast/sass.dart, lib/src/ast/sass/expression/function.dart, lib/src/ast/sass/expression/variable.dart, lib/src/ast/sass/statement/include_rule.dart, lib/src/ast/sass/statement/use_rule.dart, lib/src/ast/sass/statement/variable_declaration.dart, lib/src/parse/css.dart, lib/src/parse/parser.dart, lib/src/parse/stylesheet.dart, lib/src/visitor/async_evaluate.dart, lib/src/visitor/evaluate.dart, lib/src/visitor/find_imports.dart, lib/src/visitor/interface/statement.dart, tool/travis/sass-spec-ref.sh
See https://github.com/sass/sass-spec/pull/1341
=> Add support for parsing @use

CHANGELOG.md, lib/src/visitor/async_evaluate.dart, lib/src/visitor/evaluate.dart, pubspec.yaml
See #600
See sass/sass#2606
See https://github.com/sass/sass-spec/pull/1348
=> Deprecate assignment to non-existent global variables

CODE_OF_CONDUCT.md, README.md, package/README.npm.md, tool/grind/github.dart
See https://github.com/sass/sass-site/issues/217
Committed via https://github.com/asottile/all-repos
=> https-ify sass-lang.com urls

CHANGELOG.md, lib/src/visitor/async_evaluate.dart, lib/src/visitor/evaluate.dart, pubspec.yaml
Closes #611
See https://github.com/sass/sass-spec/pull/1352
=> Don't put style rules inside empty @keyframes rules

lib/src/async_environment.dart, lib/src/environment.dart
=> Fix some documentation issues in AsyncEnvironment

lib/src/async_environment.dart, lib/src/async_module.dart, lib/src/environment.dart, lib/src/module.dart, lib/src/visitor/async_evaluate.dart, lib/src/visitor/evaluate.dart
See https://github.com/sass/sass-spec/pull/1357
=> Emit CSS for used modules

lib/src/ast/css/modifiable/style_rule.dart, lib/src/ast/css/style_rule.dart, lib/src/ast/selector/placeholder.dart, lib/src/async_environment.dart, lib/src/async_module.dart, lib/src/environment.dart, lib/src/extend/extender.dart, lib/src/extend/extension.dart, lib/src/extend/merged_extension.dart, lib/src/module.dart, lib/src/utils.dart, lib/src/visitor/async_evaluate.dart, lib/src/visitor/evaluate.dart
See https://github.com/sass/sass-spec/pull/1359
=> Add support for @extend with @use

lib/src/ast/css/at_rule.dart, lib/src/ast/css/comment.dart, lib/src/ast/css/declaration.dart, lib/src/ast/css/import.dart, lib/src/ast/css/keyframe_block.dart, lib/src/ast/css/media_rule.dart, lib/src/ast/css/modifiable/at_rule.dart, lib/src/ast/css/modifiable/comment.dart, lib/src/ast/css/modifiable/declaration.dart, lib/src/ast/css/modifiable/import.dart, lib/src/ast/css/modifiable/keyframe_block.dart, lib/src/ast/css/modifiable/media_rule.dart, lib/src/ast/css/modifiable/node.dart, lib/src/ast/css/modifiable/style_rule.dart, lib/src/ast/css/modifiable/stylesheet.dart, lib/src/ast/css/modifiable/supports_rule.dart, lib/src/ast/css/style_rule.dart, lib/src/ast/css/stylesheet.dart, lib/src/ast/css/supports_rule.dart, lib/src/extend/empty_extender.dart, lib/src/extend/extender.dart, lib/src/visitor/async_evaluate.dart, lib/src/visitor/evaluate.dart, lib/src/visitor/interface/css.dart, lib/src/visitor/interface/modifiable_css.dart, lib/src/visitor/serialize.dart
https://github.com/sass/sass-spec/pull/1367
=> Include CSS for modules used by imported files

CHANGELOG.md, lib/src/parse/stylesheet.dart, pubspec.yaml
Closes #646
See sass/sass-spec#1384
=> Allow ! in url()s

.travis.yml, CHANGELOG.md, pubspec.yaml
=> Fix deployment infrastructure

CHANGELOG.md, lib/src/importer/node/implementation.dart, pubspec.yaml, test/node_api/importer_test.dart, test/node_api/utils.dart, test/node_api_test.dart, test/synchronize_test.dart
=> Resolve imports using custom imports before load paths

lib/src/visitor/async_evaluate.dart, lib/src/visitor/evaluate.dart
This will allow us to re-use logic for @forward. It also fixes some
usability issues where incorrect or duplicated spans were being used
for @use errors.
See sass/sass-spec#1392
=> Factor out a function to load modules

lib/src/ast/sass.dart, lib/src/ast/sass/statement/forward_rule.dart, lib/src/async_environment.dart, lib/src/environment.dart, lib/src/module/forwarded_view.dart, lib/src/parse/parser.dart, lib/src/parse/stylesheet.dart, lib/src/util/limited_map_view.dart, lib/src/util/merged_map_view.dart, lib/src/util/prefixed_map_view.dart, lib/src/util/public_member_map_view.dart, lib/src/utils.dart, lib/src/visitor/async_evaluate.dart, lib/src/visitor/evaluate.dart, lib/src/visitor/interface/statement.dart, lib/src/visitor/recursive_statement.dart
See sass/sass#1094
See #554
See sass/sass-spec#1393
=> Add support for @forward

CHANGELOG.md, lib/src/async_environment.dart, lib/src/environment.dart, lib/src/value.dart, lib/src/value/external/value.dart, lib/src/value/null.dart, lib/src/visitor/async_evaluate.dart, lib/src/visitor/evaluate.dart, pubspec.yaml
Partially addresses #554
See sass/sass-spec#1402
=> Add new module-system features for existing functions

CHANGELOG.md, lib/src/async_environment.dart, lib/src/environment.dart, lib/src/visitor/async_evaluate.dart, lib/src/visitor/evaluate.dart
See https://github.com/sass/sass-spec/pull/1409
=> Clarify !global deprecation warnings

lib/src/async_environment.dart, lib/src/environment.dart, lib/src/util/prefixed_map_view.dart, lib/src/visitor/async_evaluate.dart, lib/src/visitor/evaluate.dart
=> Address code review comments from #724

CHANGELOG.md, lib/src/async_environment.dart, lib/src/environment.dart, lib/src/visitor/async_evaluate.dart, lib/src/visitor/evaluate.dart, pubspec.yaml, tool/grind/synchronize.dart
=> Merge master into feature.use

lib/src/functions/color.dart, lib/src/functions/list.dart, lib/src/functions/map.dart, lib/src/functions/math.dart, lib/src/functions/selector.dart, lib/src/functions/string.dart, lib/src/module/built_in.dart, lib/src/visitor/async_evaluate.dart, lib/src/visitor/evaluate.dart
=> Add load-css()

CHANGELOG.md, lib/src/visitor/async_evaluate.dart, lib/src/visitor/evaluate.dart, pubspec.yaml
Closes #755
See sass/sass-spec#1429
=> Fix at-rules in nested imports

lib/src/parse/scss.dart
=> Fix typo in silent comment error message

CHANGELOG.md, lib/src/ast/sass/argument.dart, lib/src/ast/sass/argument_declaration.dart, lib/src/ast/sass/expression/function.dart, lib/src/ast/sass/expression/variable.dart, lib/src/ast/sass/statement/callable_declaration.dart, lib/src/ast/sass/statement/forward_rule.dart, lib/src/ast/sass/statement/include_rule.dart, lib/src/ast/sass/statement/variable_declaration.dart, lib/src/async_environment.dart, lib/src/color_names.dart, lib/src/environment.dart, lib/src/functions/color.dart, lib/src/module/built_in.dart, lib/src/module/forwarded_view.dart, lib/src/parse/parser.dart, lib/src/parse/stylesheet.dart, lib/src/util/limited_map_view.dart, lib/src/util/merged_map_view.dart, lib/src/util/prefixed_map_view.dart, lib/src/utils.dart, lib/src/value/argument_list.dart, lib/src/visitor/async_evaluate.dart, lib/src/visitor/evaluate.dart, perf.md, pubspec.yaml, tool/grind/benchmark.dart
See https://github.com/sass/sass-spec/pull/1437
=> Eagerly dash-normalize Sass identifiers

CHANGELOG.md, lib/src/functions/color.dart, lib/src/functions/list.dart, lib/src/functions/map.dart, lib/src/functions/string.dart, lib/src/io/vm.dart, lib/src/parse/scss.dart, lib/src/utils.dart, lib/src/value/map.dart, lib/src/visitor/async_evaluate.dart, lib/src/visitor/evaluate.dart, perf.md, pubspec.yaml, test/dart_api/value/map_test.dart, tool/grind/npm.dart, tool/travis/task/specs.sh
=> Merge origin/master into feature.use

lib/src/async_environment.dart, lib/src/environment.dart, lib/src/utils.dart
=> Improve the error message for a global member conflict

CHANGELOG.md, lib/src/visitor/async_evaluate.dart, lib/src/visitor/evaluate.dart, pubspec.yaml
Closes #792
See https://github.com/sass/sass-spec/pull/1452
=> Fix dash-insensitivity in get-function()

CHANGELOG.md, lib/src/extend/functions.dart, pubspec.yaml
=> Fix a few @extend edge cases

lib/src/ast/selector/placeholder.dart, lib/src/async_environment.dart, lib/src/environment.dart, lib/src/module/forwarded_view.dart, lib/src/parse/sass.dart, lib/src/parse/scss.dart, lib/src/parse/stylesheet.dart, lib/src/util/character.dart, lib/src/utils.dart, test/cli/shared/repl.dart, test/source_map_test.dart
See sass/sass#2731
See sass/sass-spec#1459
=> Change variable syntax to namespace.$name

CHANGELOG.md, lib/src/io/node.dart, pubspec.yaml
This produces non-negligible speed improvements for Node users with
lots of imports.
=> Check fs.existsSync() before running fs.statSync()

CHANGELOG.md, lib/src/visitor/async_evaluate.dart, lib/src/visitor/evaluate.dart, pubspec.yaml, test/dart_api/function_test.dart, test/node_api/function_test.dart
=> Dash-normalize user-defined functions

CHANGELOG.md, lib/src/executable/watch.dart, pubspec.yaml, test/cli/shared/watch.dart
=> Properly watch .css files for changes

CHANGELOG.md, lib/src/parse/parser.dart, lib/src/parse/stylesheet.dart, pubspec.yaml
See sass/sass#2738
Closes #815
See sass/sass-spec#1460
=> Properly handle some CSS identifier edge cases

CHANGELOG.md, lib/src/parse/css.dart
Closes #840
See sass/sass-spec#1483
=> Allow saturate() in plain CSS files

.travis.yml
This works around laverdet/node-fibers#420
=> Run against Node 12 rather than Node 13

CHANGELOG.md, lib/src/extend/extender.dart, pubspec.yaml
=> Propagate selector source specificity between modules

CHANGELOG.md, lib/src/visitor/find_imports.dart, pubspec.yaml, test/cli/shared/watch.dart
=> Watch files through @forward rules

.travis.yml
As suggested by https://github.com/dart-lang/sdk/issues/38334#issuecomment-542861835
=> Run Windows tests on Dart 2.6.0-dev

CHANGELOG.md, lib/src/parse/sass.dart, pubspec.yaml
Closes #874
See sass/sass-spec#1495
=> Fix inline comments in the indented syntax

CHANGELOG.md, lib/src/ast/sass.dart, lib/src/ast/sass/configured_variable.dart, lib/src/ast/sass/statement/forward_rule.dart, lib/src/ast/sass/statement/use_rule.dart, lib/src/configuration.dart, lib/src/parse/stylesheet.dart, lib/src/util/merged_map_view.dart, lib/src/visitor/async_evaluate.dart, lib/src/visitor/evaluate.dart, lib/src/visitor/recursive_ast.dart
=> Support @forward ... with

CHANGELOG.md, lib/src/functions/math.dart
See https://github.com/sass/sass-spec/pull/1502
=> Add exponential math functions.

CHANGELOG.md, lib/src/node.dart, pubspec.yaml, test/node_api/source_map_test.dart
=> Don't try to resolve relative Node importer URLs for source maps

CHANGELOG.md, lib/src/functions/math.dart
See https://github.com/sass/sass-spec/pull/1504
=> Add trigonometric math functions.

CHANGELOG.md, lib/src/async_environment.dart, lib/src/environment.dart, lib/src/module.dart, lib/src/module/built_in.dart, lib/src/module/forwarded_view.dart, lib/src/module/shadowed_view.dart, pubspec.yaml
See sass/sass-spec#1511
See sass/sass#2820
Closes #946
=> Don't throw conflict errors for identical members

lib/src/async_environment.dart, lib/src/environment.dart
See #946
See sass/sass#2820
See sass/sass-spec#1512
=> Properly check for double-forwarded functions and mixins

CHANGELOG.md, lib/src/parse/stylesheet.dart
Closes #934
See sass/sass#2800
See sass/sass-spec#1514
=> Don't include leading underscores in implicit namespaces

tool/grind.dart
This got dropped in the move to cli_pkg.
=> Add a release header

CHANGELOG.md, lib/src/node.dart, lib/src/node/exports.dart, pubspec.yaml, test/node_api/api.dart, test/node_api/value/boolean_test.dart, test/node_api/value/null_test.dart
=> Add missing constants to JS API

CHANGELOG.md, lib/src/parse/stylesheet.dart, lib/src/utils.dart, pubspec.yaml
Fixes #1038.
See sass/sass-spec#1547.
=> Fix a null pointer bug

CHANGELOG.md, lib/src/parse/parser.dart, tool/grind.dart
See https://github.com/sass/sass-spec/pull/1548
=> Improve the error messages for syntax errors

CHANGELOG.md, lib/src/functions/map.dart, pubspec.yaml
See https://github.com/sass/sass-spec/pull/1559
=> Add support for nested maps to map-get

CHANGELOG.md, lib/src/functions/map.dart, pubspec.yaml
See https://github.com/sass/sass-spec/pull/1558
=> Add support for nested maps to has-key

CHANGELOG.md, lib/src/functions/map.dart
See https://github.com/sass/sass/pull/2836
See https://github.com/sass/sass-spec/pull/1561
=> Add a map.set() function

CHANGELOG.md, lib/src/value/color.dart, lib/src/value/external/color.dart, pubspec.yaml, test/dart_api/value/color_test.dart
=> Support HWB colors in SassColor

CHANGELOG.md, lib/src/parse/stylesheet.dart, pubspec.yaml
Closes #1086
See sass/sass-spec#1567
=> Produce a better error for positional arguments after named

CHANGELOG.md, lib/src/functions/map.dart
See https://github.com/sass/sass/pull/2836
See https://github.com/sass/sass-spec/pull/1566
=> Adds nested map support to map-merge.

CHANGELOG.md, lib/src/functions/map.dart
See sass/sass#1739
See #1088
See https://github.com/sass/sass-spec/pull/1569
=> Add a map.deep-remove() function

lib/src/functions/color.dart
See sass/sass#2834
See #1089
See sass/sass-spec#1571
=> Add a color.hwb() function

CHANGELOG.md, lib/src/ast/css/declaration.dart, lib/src/ast/css/modifiable/declaration.dart, lib/src/ast/sass/statement/declaration.dart, lib/src/parse/stylesheet.dart, lib/src/visitor/async_evaluate.dart, lib/src/visitor/clone_css.dart, lib/src/visitor/evaluate.dart, lib/src/visitor/serialize.dart, pubspec.yaml
Closes #1095
See sass/sass-spec#1572
=> Fix a bug with nested properties beneath Sass-syntax custom props

CHANGELOG.md, lib/src/functions/map.dart, lib/src/value.dart, lib/src/value/external/value.dart, lib/src/value/list.dart, lib/src/value/map.dart, pubspec.yaml, test/dart_api/value/boolean_test.dart, test/dart_api/value/color_test.dart, test/dart_api/value/function_test.dart, test/dart_api/value/list_test.dart, test/dart_api/value/map_test.dart, test/dart_api/value/null_test.dart, test/dart_api/value/number_test.dart, test/dart_api/value/string_test.dart
Closes #1088
See https://github.com/sass/sass-spec/pull/1574
=> Merge support for nested map functions

pubspec.yaml, tool/grind.dart, tool/grind/utils.dart
This should fix the release note errors we've been seeing on the
feature.hwb branch.
=> Use cli_pkg 1.0.0-beta.10

CHANGELOG.md, lib/src/functions/color.dart
See sass/sass#2834
See #1089
See https://github.com/sass/sass-spec/pull/1576
=> Add color.whiteness() and color.blackness() functions

CHANGELOG.md, lib/src/ast/sass/at_root_query.dart, lib/src/parse/stylesheet.dart, lib/src/visitor/async_evaluate.dart, lib/src/visitor/evaluate.dart, pubspec.yaml
=> Fix a buggy interaction between @at-root and @keyframes

CHANGELOG.md, lib/src/async_compile.dart, lib/src/compile.dart, lib/src/executable/watch.dart, lib/src/importer/filesystem.dart, lib/src/io.dart, pubspec.yaml, test/cli/shared/source_maps.dart
=> Avoid always downcasing file paths on Windows

CHANGELOG.md, lib/src/parse/stylesheet.dart, lib/src/value/string.dart, pubspec.yaml
Closes #1146
See sass/sass#2860
See sass/sass-spec#1605
=> Add support for clamp() as a special math function

README.md
=> Add a Gitter link to the README

CHANGELOG.md, lib/src/visitor/async_evaluate.dart, lib/src/visitor/evaluate.dart, pubspec.yaml
Closes #1199 
https://github.com/sass/sass-spec/pull/1617
=> Implement proper handling of units in for loops

CHANGELOG.md, lib/src/functions/string.dart, pubspec.yaml
https://github.com/sass/sass-spec/pull/1642
=> Fix argument names in str-slice errors

CHANGELOG.md, lib/src/visitor/find_dependencies.dart, pubspec.yaml, test/cli/shared/update.dart
=> Fix bug in --update with built-in modules

test/compressed_test.dart
=> Delete duplicate test cases

CHANGELOG.md, lib/src/async_environment.dart, lib/src/environment.dart, pubspec.yaml
Closes #1250
See https://github.com/sass/sass-spec/pull/1669
=> Fix a variable-assignment bug

CHANGELOG.md, lib/src/parse/stylesheet.dart, test/dart_api/importer_test.dart, test/node_api/importer_test.dart
=> Fix root-relative @import URLs as passed to importers

README.md
Closes https://github.com/sass/sass-site/issues/560
=> Add links to CLI docs in README

CHANGELOG.md, lib/src/extend/extension_store.dart
Closes #1301
See https://github.com/sass/sass-spec/pull/1673
=> Properly support selector lists for selector.extend()

CHANGELOG.md, lib/src/exception.dart
=> Strip CRLFs from error comments

CHANGELOG.md, lib/src/parse/parser.dart, lib/src/parse/stylesheet.dart
Closes #1399
See sass/sass-spec#1682
=> Fix backslash-escapes in url()s

CHANGELOG.md, lib/src/parse/parser.dart
Closes #1423
See sass/sass-spec#1681
=> Fix a single-backslash attribute selector

CHANGELOG.md, lib/src/util/character.dart, lib/src/visitor/serialize.dart, test/compressed_test.dart, test/output_test.dart
=> Emit escape sequences for private-use characters in expanded mode

CHANGELOG.md, lib/src/extend/extension_store.dart, lib/src/node.dart, lib/src/utils.dart, test/node_api/importer_test.dart
We weren't properly merging multiple @extend rules that were added to an
upstream module at the same time, so some of them weren't being marked as
satisfied.
Closes #1393
See sass/sass-spec#1686
=> Fix a couple bugs with @extend

CHANGELOG.md, lib/src/ast/sass.dart, lib/src/ast/sass/expression/binary_operation.dart, lib/src/ast/sass/expression/calculation.dart, lib/src/functions/meta.dart, lib/src/parse/css.dart, lib/src/parse/stylesheet.dart, lib/src/value.dart, lib/src/value/calculation.dart, lib/src/value/number.dart, lib/src/value/number/complex.dart, lib/src/value/number/single_unit.dart, lib/src/value/number/unitless.dart, lib/src/visitor/async_evaluate.dart, lib/src/visitor/evaluate.dart, lib/src/visitor/interface/expression.dart, lib/src/visitor/interface/value.dart, lib/src/visitor/serialize.dart, pkg/sass_api/CHANGELOG.md, pkg/sass_api/pubspec.yaml, pubspec.yaml
See sass/sass#818
See sass/sass-spec#1688
=> Add support for first-class calc()

CHANGELOG.md, lib/src/parse/stylesheet.dart, pkg/sass_api/CHANGELOG.md, pkg/sass_api/pubspec.yaml, pubspec.yaml
See sass/sass#3142
See sass/sass-spec#1702
=> Emergency fix: Temporarily drop support for min/max calculations

CHANGELOG.md, lib/src/ast/selector/pseudo.dart, lib/src/ast/selector/simple.dart, lib/src/ast/selector/universal.dart, pubspec.yaml
See sass/sass#3134
See sass/sass-spec#1700
=> Improve unification of :host and :host-context

CHANGELOG.md, lib/src/value/calculation.dart, pkg/sass_api/CHANGELOG.md, pkg/sass_api/pubspec.yaml, pubspec.yaml
See sass/sass#3142
See sass/sass#3146
See sass/sass-spec#1705
=> Allow the + operator for calculations and strings

CHANGELOG.md, lib/src/visitor/async_evaluate.dart, lib/src/visitor/evaluate.dart, pkg/sass_api/CHANGELOG.md, pkg/sass_api/pubspec.yaml, pubspec.yaml
See sass/sass#3153
See sass/sass#3154
See sass/sass-spec#1714
=> Preserve parentheses around var() functions in calculations

CHANGELOG.md, lib/src/parse/stylesheet.dart, pkg/sass_api/CHANGELOG.md, pkg/sass_api/pubspec.yaml, pubspec.yaml
Closes #1499
See sass/sass-spec#1715
=> Fix interpolation lookahead for calculations

lib/src/importer/legacy_node.dart, lib/src/node.dart, lib/src/node/array.dart, lib/src/node/compile.dart, lib/src/node/compile_options.dart, lib/src/node/compile_result.dart, lib/src/node/exception.dart, lib/src/node/exports.dart, lib/src/node/legacy.dart, lib/src/node/legacy/value.dart, lib/src/node/source_span.dart, lib/src/node/url.dart, lib/src/node/utils.dart, pubspec.yaml, test/legacy_node_api/value/utils.dart, tool/grind.dart
=> Add basic compile functions for the new JS API

lib/src/importer/node_to_dart/async.dart, lib/src/importer/node_to_dart/async_file.dart, lib/src/importer/node_to_dart/file.dart, lib/src/importer/node_to_dart/sync.dart, lib/src/node/compile.dart, lib/src/node/compile_options.dart, lib/src/node/importer.dart, lib/src/node/utils.dart
See sass/sass#2509
See sass/sass-spec#1727
=> Add support for the new importer API

lib/src/node/compile.dart, lib/src/node/compile_options.dart, lib/src/node/legacy.dart, lib/src/parse/stylesheet.dart
=> Add support for custom functions in the new JS API

CHANGELOG.md, package/package.json, pkg/sass_api/CHANGELOG.md, pkg/sass_api/pubspec.yaml, pubspec.yaml, tool/grind.dart, tool/grind/bazel.dart, tool/grind/benchmark.dart, tool/grind/frameworks.dart, tool/grind/utils.dart
=> Add TypeScript type declarations to the npm package

CHANGELOG.md, lib/src/parse/keyframe_selector.dart, lib/src/value/list.dart, pkg/sass_api/pubspec.yaml, pubspec.yaml
https://github.com/sass/sass-spec/pull/1740
Fixes https://github.com/sass/sass/issues/3160
=> Let inspect() print nested, empty, bracketed lists.

CHANGELOG.md, lib/src/ast/sass/supports_condition/declaration.dart, lib/src/parse/stylesheet.dart, lib/src/visitor/async_evaluate.dart, lib/src/visitor/evaluate.dart, pubspec.yaml
Closes sass/sass#3216
See sass/sass-spec#1747
=> Properly parse custom property values in @supports conditions

CHANGELOG.md, lib/src/logger/node_to_dart.dart, pkg/sass_api/CHANGELOG.md, pkg/sass_api/pubspec.yaml, pubspec.yaml
=> Pass undefined span instead of null to Logger.warn() in JS

CHANGELOG.md, pkg/sass_api/pubspec.yaml, pubspec.yaml
=> Mention TypeScript type updates in the CHANGELOG

CHANGELOG.md, pkg/sass_api/CHANGELOG.md, pkg/sass_api/pubspec.yaml, pubspec.yaml, test/legacy_node_api/source_map_test.dart
=> Cut a release with TS definitions for TRUE/FALSE

CHANGELOG.md, pkg/sass_api/CHANGELOG.md, pkg/sass_api/pubspec.yaml, pubspec.yaml
=> Cut a release with a TS definition for NULL

CHANGELOG.md, lib/src/node/compile.dart, lib/src/node/compile_options.dart
See https://github.com/sass/sass/pull/3226
See https://github.com/sass/sass-spec/pull/1757
=> Implement the sourceMapIncludeSources JS option

CHANGELOG.md, pkg/sass_api/CHANGELOG.md, pkg/sass_api/pubspec.yaml, pubspec.yaml
This also adds a CHANGELOG entry for the TS declaration fix for
LegacyPluginThis.options.linefeed.
=> Cut a release

CHANGELOG.md, package/package.json, pkg/sass_api/pubspec.yaml, pubspec.yaml
Fixes https://github.com/sass/dart-sass/issues/1604
=> Drop support for non-LTS Node (< 12).

CHANGELOG.md, lib/src/node/compile.dart, lib/src/visitor/async_evaluate.dart, lib/src/visitor/evaluate.dart, pkg/sass_api/CHANGELOG.md, pkg/sass_api/pubspec.yaml, pubspec.yaml
Fixes #1628.
See https://github.com/sass/sass-spec/pull/1778
=> Fix CSS import bug

CHANGELOG.md, pkg/sass_api/CHANGELOG.md, pkg/sass_api/pubspec.yaml, pubspec.yaml
=> Add changelog for PR #849 about preserving trailing loud comment location

CHANGELOG.md, lib/src/extend/functions.dart, pkg/sass_api/CHANGELOG.md, pkg/sass_api/pubspec.yaml, pubspec.yaml
Closes #969
See sass/sass-spec#1811
=> Ensure that selectors like :root always unify to the beginning

CHANGELOG.md, lib/src/extend/functions.dart, pkg/sass_api/CHANGELOG.md, pkg/sass_api/pubspec.yaml, pubspec.yaml
Closes #791
See sass/sass-spec#1814
=> Improve combinator superselector logic

CHANGELOG.md, lib/src/parse/stylesheet.dart, pkg/sass_api/CHANGELOG.md, pkg/sass_api/pubspec.yaml, pubspec.yaml
See https://github.com/sass/sass-spec/pull/1822
=> Fix span for not operations

CHANGELOG.md, lib/src/functions/color.dart
See #1174
See sass/sass#2904
See sass/sass-spec#1831
=> Support all angle units in color functions

CHANGELOG.md, lib/src/parse/stylesheet.dart, pkg/sass_api/CHANGELOG.md, pkg/sass_api/pubspec.yaml, pubspec.yaml
Closes #1728
See https://github.com/sass/sass/issues/2538
See sass/sass-spec#1833
[skip dart-sass]
=> Add full support for Media Queries 4

CHANGELOG.md, pkg/sass_api/CHANGELOG.md, pkg/sass_api/pubspec.yaml, pubspec.yaml
See https://github.com/sass/embedded-host-node/pull/167/files
=> Update CHANGELOG for embedded-host-node fixes

lib/src/parse/stylesheet.dart
=> Delete dead code

CHANGELOG.md, lib/src/visitor/serialize.dart, pkg/sass_api/CHANGELOG.md, pkg/sass_api/pubspec.yaml, pubspec.yaml
See https://github.com/sass/sass-spec/pull/1862
Closes https://github.com/sass/sass/issues/3448
=> Remove sourcemap comments from Sass sources

CHANGELOG.md, lib/src/extend/functions.dart
=> Fix an edge case in superselector computation

CONTRIBUTING.md, bin/sass.dart, lib/src/parse/parser.dart, lib/src/parse/stylesheet.dart, lib/src/value/color.dart, lib/src/value/number.dart, lib/src/visitor/async_evaluate.dart, lib/src/visitor/evaluate.dart, lib/src/visitor/find_dependencies.dart
This PR fixes typos I spotted in a few files. It also changes a few link from `http`to `https`protocol.
=> Fixes typos

CHANGELOG.md, lib/src/ast/sass/argument_invocation.dart, lib/src/ast/sass/expression/binary_operation.dart, lib/src/ast/sass/expression/list.dart, lib/src/ast/sass/expression/unary_operation.dart, lib/src/visitor/async_evaluate.dart, lib/src/visitor/evaluate.dart, lib/src/visitor/expression_to_calc.dart, lib/src/visitor/replace_expression.dart, pkg/sass_api/CHANGELOG.md, pkg/sass_api/lib/sass_api.dart, pkg/sass_api/pubspec.yaml, pubspec.yaml
Closes #1887
See https://github.com/sass/sass-spec/pull/1882
=> Improve the suggested replacements for unary minus in /-as-division

.github/workflows/ci.yml, CHANGELOG.md, lib/src/executable/compile_stylesheet.dart, lib/src/utils.dart, test/cli/shared/update.dart, test/cli/shared/watch.dart
=> Add timestamp to printed compile statement

CHANGELOG.md, lib/src/deprecation.dart, lib/src/parse/stylesheet.dart, pkg/sass_api/CHANGELOG.md, pkg/sass_api/pubspec.yaml, pubspec.yaml
See #604
See sass/sass#2607
See sass/sass-spec#1897
=> Deprecate duplicate !global and !default declarations

lib/src/parse/scss.dart, pkg/sass_api/CHANGELOG.md, pkg/sass_api/pubspec.yaml, pubspec.yaml
=> Split SilentComment nodes on empty lines in SCSS

lib/sass.dart
Dart 3.0.1 just got released and it has a few changes with `dart format`:
https://github.com/dart-lang/sdk/blob/main/CHANGELOG.md#301
=> Format with dart 3.0.1

README.md
=> Update README: install with brew on macOS or Linux

CHANGELOG.md, pubspec.yaml, tool/grind.dart
=> Use the new import name for the ESM default export

CHANGELOG.md, lib/src/ast/css/modifiable/node.dart, lib/src/async_environment.dart, lib/src/environment.dart, lib/src/module.dart, lib/src/module/built_in.dart, lib/src/module/forwarded_view.dart, lib/src/module/shadowed_view.dart, lib/src/visitor/async_evaluate.dart, lib/src/visitor/evaluate.dart, lib/src/visitor/serialize.dart
See sass/sass#2848
See sass/sass-spec#1919
Closes #1939
=> Emit comments in source order where possible

.github/workflows/ci.yml, CHANGELOG.md, pkg/sass_api/CHANGELOG.md, pkg/sass_api/pubspec.yaml, pubspec.yaml
=> Include protobuf definitions in the pub package

.pubignore, CHANGELOG.md, pubspec.yaml
=> Add a pubignore so pub knows to publish protobuf files

CHANGELOG.md, pkg/sass_api/CHANGELOG.md, pkg/sass_api/pubspec.yaml, pubspec.yaml
We should have billing set up for the M1 MacOS runners now.
=> Cut another release

lib/src/functions/color.dart
See sass/sass#3673
See sass/sass-spec#1947
=> Add support for relative color syntax

CHANGELOG.md, lib/src/embedded/compilation_dispatcher.dart
https://github.com/sass/sass/pull/3773
=> Support CompileRequest.silent of embedded protocol

package.json
This was accidentally added for local testing.
=> Remove the sass dependency from package.json

CHANGELOG.md, pubspec.yaml
See https://github.com/sass/sass/issues/2739
=> Update pubspec/changelog for `pkg:` importers

.github/workflows/build-linux-musl.yml, CHANGELOG.md, pkg/sass_api/CHANGELOG.md, pkg/sass_api/pubspec.yaml, pubspec.yaml
=> Fix linux musl builds

CHANGELOG.md, lib/src/ast/sass/expression/variable.dart, pkg/sass_api/CHANGELOG.md, pkg/sass_api/pubspec.yaml, pubspec.yaml
=> Preserve underscores in `VariableExpression.toString()`

lib/src/functions/color.dart
=> Quote channel names in color functions

lib/src/value/color/gamut_map_method/local_minde.dart, lib/src/visitor/serialize.dart
=> Fix bugs caught by to-gamut() tests

lib/src/functions/color.dart
=> Don't case-normalize channel names, per spec

CHANGELOG.md, lib/src/visitor/async_evaluate.dart, lib/src/visitor/evaluate.dart, pkg/sass_api/CHANGELOG.md, pkg/sass_api/pubspec.yaml, pubspec.yaml
See sass/sass#3859
See sass/sass#3861
See sass/sass-spec#1987
=> Allow at-rules in `@keyframes` blocks

CHANGELOG.md, lib/src/executable/compile_stylesheet.dart, lib/src/executable/repl.dart, pkg/sass_api/CHANGELOG.md, pkg/sass_api/pubspec.yaml, pubspec.yaml, test/cli/dart/deprecations_test.dart, test/cli/node/deprecations_test.dart, test/cli/shared/deprecations.dart, test/double_check_test.dart
=> Fix deprecation flags in the CLI and add tests

CHANGELOG.md, lib/src/embedded/compilation_dispatcher.dart, pkg/sass_api/CHANGELOG.md, pkg/sass_api/pubspec.yaml, pubspec.yaml
https://github.com/sass/sass/pull/3868
https://github.com/sass/embedded-host-node/pull/299
=> Parse Deprecation.forVersion on compiler side

.github/workflows/build-android.yml, .github/workflows/build-linux-musl.yml, .github/workflows/build-linux.yml, .github/workflows/build-macos.yml, .github/workflows/build-windows.yml
=> Build AOT releases with native arm64 runners

.github/util/initialize/action.yml
This PR simplifies the logic and removes duplicated code in CI.
=> Refactor duplicated code in CI

lib/src/embedded/isolate_dispatcher.dart
This PR fixes a bug where multiple isolates may be spawned for the same compilation id due to async gap between checking `_activeIsolates[compilationId]` and assigning `_activeIsolates[compilationId] = isolate;`, if the host sends packets with the same compilation id extremely quickly.
Current buggy behavior:
- Packet A (compilationId: 1): `_activeIsolates[compilationId] is null`, spawning new isolate asynchronously.
- Packet B (compilationId: 1): `_activeIsolates[compilationId] is null`, spawning new isolate asynchronously.
- Packet A (compilationId: 1): new isolate spawned, `_activeIsolates[compilationId] = isolate;`.
- Packet B (compilationId: 1): new isolate spawned, `_activeIsolates[compilationId] = isolate;`.
Fixed:
- Packet A (compilationId: 1): `_activeIsolates[compilationId] is …
=> Fix duplicated isolates for the same compilation id

CHANGELOG.md, lib/src/functions/color.dart, pkg/sass-parser/CHANGELOG.md, pkg/sass-parser/package.json, pkg/sass_api/CHANGELOG.md, pkg/sass_api/pubspec.yaml, pubspec.yaml
Closes #2358
See sass/sass-spec#2020
=> Quote `$channel` in channel function replacement suggestions

.github/workflows/release.yml
Fixes this warning: https://github.com/sass/dart-sass/actions/runs/11392650220/job/31699633395#step:3:1
=> Fix setup-node

CHANGELOG.md, lib/src/deprecation.dart, lib/src/js/deprecations.dart, lib/src/parse/css.dart, lib/src/parse/stylesheet.dart, pkg/sass-parser/CHANGELOG.md, pkg/sass-parser/package.json, pkg/sass_api/CHANGELOG.md, pkg/sass_api/pubspec.yaml, pubspec.yaml, test/deprecations_test.dart
See https://github.com/sass/sass/pull/3976
See https://github.com/sass/sass-spec/pull/2035
Closes #378
=> Drop support for special `@-moz-document` parsing

pkg/sass_api/pubspec.yaml, pubspec.yaml
See https://github.com/dart-lang/dartdoc/issues/3947
=> Avoid a broken Dartdoc release

pkg/sass_api/pubspec.yaml, pubspec.yaml
The bug we were working around has been fixed in dart-lang/dartdoc#3951.
=> Support the latest DartDoc

CHANGELOG.md, lib/src/logger.dart, lib/src/logger/stderr.dart, pkg/sass-parser/CHANGELOG.md, pkg/sass-parser/package.json, pkg/sass_api/CHANGELOG.md, pkg/sass_api/pubspec.yaml, pubspec.yaml
=> Include deprecation IDs in deprecation messages

CHANGELOG.md, lib/src/visitor/async_evaluate.dart, lib/src/visitor/evaluate.dart, pkg/sass-parser/CHANGELOG.md, pkg/sass-parser/package.json, pkg/sass_api/CHANGELOG.md, pkg/sass_api/pubspec.yaml, pubspec.yaml, test/cli/shared.dart
=> Fix `--quiet-deps` for `@content` blocks

.github/workflows/release.yml, pkg/sass-parser/CHANGELOG.md
Previously this deployed an empty package.
Closes #2485
=> Compile sass-parser before deploying

CHANGELOG.md
See https://github.com/sass/embedded-host-node/pull/359
=> Add changelog for embedded host fix of the SassBoolean type

CHANGELOG.md, lib/src/deprecation.dart, lib/src/parse/scss.dart, test/cli/shared/deprecations.dart, test/deprecations_test.dart, test/embedded/protocol_test.dart
See https://github.com/sass/sass/pull/4057
See https://github.com/sass/sass-spec/pull/2054
=> Drop support for `@elseif`

CHANGELOG.md, lib/src/importer/node_package.dart, pkg/sass-parser/CHANGELOG.md, pkg/sass-parser/package.json, pkg/sass_api/CHANGELOG.md, pkg/sass_api/pubspec.yaml, pubspec.yaml
See sass/sass#4080
See sass/sass-spec#2059
=> Allow the Node.js pkg importer to return the same URL multiple times
